blog/urls.py
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from django.urls import path
from . import views
from blog.views import PostListView, PostDetailView, index

app_name = BlogConfig.name

urlpatterns = [
    path('<int:pk>/', cache_page(60)(PostDetailView.as_view()), name='post_detail'),
    path('', views.index, name='index'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
                  path('', include('blog.urls', namespace='blog')),
                  path('admin/', admin.site.urls),
                  path('mailing/', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# path('users/', include('users.urls', namespace='users')),
# path('blog/', include('blog.urls', namespace='blog')),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.timezone import now

from mailing.models import NULLABLE


class Post(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    content = models.TextField(verbose_name='содержимое', **NULLABLE)
    preview = models.ImageField(upload_to='posts/', verbose_name='изображение', default="posts/nophoto.png")
    date_of_creation = models.DateTimeField(default=now, verbose_name='дата создания')
    number_of_views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title}'

    def increment_count_view(self):
        self.number_of_views += 1
        self.save()

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'
        ordering = ('-date_of_creation',)

blog/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from django.core.cache import cache
from blog.models import Post
from mailing.models import Mailing


class PostListView(ListView):
    model = Post
    extra_context = {
        'title': 'Список постов'
    }


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        post_id = self.kwargs['pk']
        cache_key = f'post_{post_id}'
        post = cache.get(cache_key)

        if not post:
            post = super().get_object(queryset=queryset)
            post.increment_count_view()
            cache.set(cache_key, post)

        return post

    # def get_object(self, queryset=None):
    #     post = super().get_object(queryset=queryset)
    #     post.increment_count_view()
    #     return post



def index(request):
    # Получаем количество рассылок всего
    total_mailings = Mailing.objects.count()

    # Получаем количество активных рассылок
    active_mailing = Mailing.objects.filter(is_active=True).count()

    # Получаем количество уникальных клиентов для рассылок
    unique_clients = Mailing.objects.values('clients').distinct().count()

    # Получаем 3 случайные статьи из блога
    random_post = Post.objects.order_by('?')[:3]

    # Передаем полученную информацию в шаблон
    context = {
        'total_mailings': total_mailings,
        'active_mailing': active_mailing,
        'unique_clients': unique_clients,
        'random_post': random_post,
        'title': 'Главная страница'
    }
    return render(request, 'index.html', context=context)

blog/templates/includes/inc_blog_card_post.html
{% load mediapath %}
<div class="col-lg-12 m-2">
    <div class="card text-center">
        <h3 class="card-header">
            {{ post.title | title }}
        </h3>
        <div class="card-body">
            <img class="img-fluid "
                    {% if post.preview %}
                 src="{{ post.preview | media_path }}"
                 alt="Упс." width="140" height="140"

                    {% endif %}
                    {% if post.preview == 'posts/nophoto.png' %}
                 alt="Упс." width="140" height="140"
                    {% endif %}
            >
            <div class="content m-2">
                <p class="card-text t-2">{{ post.content | truncatechars:150 }}</p>
            </div>
            <div class="content text-right">

                <a href="{% url 'blog:post_detail' post.pk %}" class="btn btn-dark text-right btn-sm">Читать далее</a>

            </div>
        </div>
        <div class="card-footer text-muted text-left">
            <div class="container">
                <div class="row align-items-start">
                    <div class="col">
                        {{ post.date_of_creation }}
                    </div>
                    <div class="col text-right">
                        &#128065;&#65039; {{ post.number_of_views }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>