blog/urls.py
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from django.urls import path
from . import views
from blog.views import PostListView, PostDetailView, index

app_name = BlogConfig.name

urlpatterns = [
    path('<int:pk>/', cache_page(60)(PostDetailView.as_view()), name='post_detail'),
    path('', views.index, name='index'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
                  path('', include('blog.urls', namespace='blog')),
                  path('admin/', admin.site.urls),
                  path('mailing/', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# path('users/', include('users.urls', namespace='users')),
# path('blog/', include('blog.urls', namespace='blog')),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from mailing.apps import MailingConfig
from django.urls import path
from . import views

from mailing.views import MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingDetailView, \
    ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, AttemptListView, \
    AttemptDetailView

app_name = MailingConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('create/', MailingCreateView.as_view(), name='mailing_create'),
    path('update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('attempt/', AttemptListView.as_view(), name='attempt_list'),
    path('attempt/<int:pk>/', AttemptDetailView.as_view(), name='attempt_view'),
]

mailing/models.py
from django.db import models
from config import settings
from django.utils.timezone import now


NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='имя', **NULLABLE)
    last_name = models.CharField(max_length=150, verbose_name='фамилия', **NULLABLE)
    email = models.EmailField(max_length=150, verbose_name='почта', **NULLABLE)
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='кем создан', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активен')

    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailing(models.Model):
    ONCE = 'один раз'  # временно
    DAILY = 'раз в день'
    WEEKLY = 'раз в неделю'
    MONTHLY = 'раз в месяц'

    FREQUENCY_CHOICES = [
        (ONCE, 'один раз'),
        (DAILY, 'раз в день'),
        (WEEKLY, 'раз в неделю'),
        (MONTHLY, 'раз в месяц'),
    ]

    CREATED = 'Создана'
    LAUNCHED = 'Запущена'
    COMPLETED = 'Завершена'

    SELECT_STATUS = [
        (CREATED, 'Создана'),
        (LAUNCHED, 'Запущена'),
        (COMPLETED, 'Завершена'),
    ]

    date_of_creation = models.DateTimeField(default=now, verbose_name='Дата создания')
    start_date = models.DateField(default=now, verbose_name='Дата начала рассылки')
    end_date = models.DateField(default=now, verbose_name='Дата окончания рассылки', **NULLABLE)
    frequency = models.CharField(max_length=14, choices=FREQUENCY_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=50, default='Создана', choices=SELECT_STATUS, verbose_name='Статус')
    clients = models.ManyToManyField(Client)
    title = models.CharField(max_length=50, verbose_name='Название рассылки', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Кем создана', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активна')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            (
                "can_view_any_mailings",
                "Сan view any mailings"
            ),
            (
                "can_disable_mailings",
                "Can disable mailings"
            )]


class Message(models.Model):
    subject = models.CharField(max_length=254, verbose_name='Тема')
    message = models.TextField(verbose_name='Сообщение')
    date_of_creation = models.DateTimeField(default=now, verbose_name='дата создания')
    mailing = models.ForeignKey(Mailing, verbose_name='рассылка', on_delete=models.CASCADE)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Attempt(models.Model):
    DELIVERED = 'delivered'
    NOT_DELIVERED = 'not_delivered'

    STATUS = (
        (DELIVERED, 'доставлено'),
        (NOT_DELIVERED, 'не доставлено'),
    )

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')
    time_of_sent = models.DateTimeField(default=now, verbose_name='Время рассылки')
    status = models.CharField(max_length=100, choices=STATUS, verbose_name='Статус')
    response = models.TextField(verbose_name='Ответ сервера', **NULLABLE)

    def __str__(self):

        return f"{message.subject} - {self.time_of_sent}"

    def get_email(self):
        message = Message.objects.get(mailing=self.mailing)
        # client = Client.objects.get(mailing=self.mailing)
        client = self.mailing.clients.first()
        return f'{client.email}'

    class Meta:
        verbose_name = 'Попытка отправки'
        verbose_name_plural = 'Попытки отправки'

mailing/forms.py
from django import forms

from mailing.models import Mailing, Message, Client


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        # fields = '__all__'
        exclude = ('date_of_creation', 'owner',)


class MailingFormManager(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('is_active',)


class MessageForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'


class MessageDetailForm(FormStyleMixin, forms.ModelForm):
    subject = forms.CharField(label='Тема письма',
                              widget=forms.Textarea(attrs={'cols': 40, 'rows': 2, 'readonly': 'readonly'}))
    message = forms.CharField(label='Сообщение',
                              widget=forms.Textarea(attrs={'cols': 40, 'rows': 3, 'readonly': 'readonly'}))

    date_of_creation = forms.DateTimeField(label='Дата создания',
                                           widget=forms.Textarea(attrs={'cols': 40, 'rows': 1, 'readonly': 'readonly'}))

    class Meta:
        model = Message
        fields = ('subject', 'message', 'date_of_creation')


class ClientForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Client
        # fields = '__all__'
        exclude = ('date_of_creation', 'owner',)

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from mailing.forms import MailingForm, MessageForm, MessageDetailForm, ClientForm, MailingFormManager
from mailing.models import Mailing, Message, Client, Attempt
from users.models import User


# Create your views here.
class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    extra_context = {
        'title': 'Список рассылок'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        # user1 = User.objects.get(email='iaiznura@gmail.com')
        # permissions = user1.get_all_permissions()
        # print(permissions)
        manager = self.request.user.has_perm("mailing.can_view_any_mailings") and self.request.user.is_authenticated
        if manager:
            return queryset
        else:
            # queryset = queryset.filter(owner=self.request.user, is_active=True)
            queryset = queryset.filter(owner=self.request.user)
            return queryset


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(Mailing, Message, form=MessageDetailForm, extra=0, can_delete=False)
        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            MessageFormset = inlineformset_factory(Mailing, Message, form=MessageDetailForm, extra=0, can_delete=False)
            context_data['formset'] = MessageFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    # fields = ('title', 'frequency', 'status',)
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')
    extra_context = {
        'title': 'Создание рассылки'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(Mailing, Message, form=MessageForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        form.instance.owner = self.request.user if self.request.user.is_authenticated else None
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_form.html"
    success_url = reverse_lazy('mailing:mailing_list')
    extra_context = {
        'title': 'Редактирование'
    }

    def get_form_class(self):
        class_form = MailingFormManager
        mailing = self.get_object()
        if not self.request.user.has_perm('mailing.can_disable_mailings'):
            class_form = MailingForm
        if self.request.user == mailing.owner or self.request.user.is_superuser:
            class_form = MailingForm
        return class_form

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(Mailing, Message, form=MessageForm, extra=1, max_num=1)
        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)
        return context_data

    def test_func(self):
        mailing = self.get_object()
        manager = self.request.user.has_perm(
            "mailing.can_view_any_mailings") and self.request.user.has_perm(
            'mailing.can_disable_mailings')
        if manager:
            return True
        else:
            return self.request.user == mailing.owner

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        form.instance.author = self.request.user if self.request.user.is_authenticated else None
        return super().form_valid(form)


class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')

    def test_func(self):
        mailing = self.get_object()
        if self.request.user.is_superuser:
            return True
        else:
            return self.request.user == mailing.owner


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {
        'title': 'Список клиентов'
    }


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('first_name', 'last_name', 'email', 'comment',)
    # form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')
    extra_context = {
        'title': 'Создание рассылки'
    }

    def handle_no_permission(self):
        raise PermissionDenied("Вы не являетесь автором этого продукта.")


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    # fields = ('first_name', 'last_name', 'email', 'comment',)
    form_class = ClientForm
    template_name = "mailing/client_form.html"
    success_url = reverse_lazy('mailing:client_list')
    extra_context = {
        'title': 'Редактирование'
    }


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:mailing_list')


class AttemptListView(LoginRequiredMixin, ListView):
    model = Attempt
    extra_context = {
        'object_list': Attempt.objects.all(),
        'title': 'Статус рассылок'
    }


class AttemptDetailView(LoginRequiredMixin, DetailView):
    model = Attempt
    extra_context = {
        'title': 'Рассылка'
    }

mailing/templates/mailing/attempt_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="card text-center">
        <div class="card-header text-center">Email отправки - {{ object.get_email }}</div>
        <div class="card-body">
            <table class="table table-striped">
                <div class="card rounded-3 shadow-sm">
                        <h6> Время отправки: {{ object.time_of_sent }}</h6>
                        <h6 class="card-title">Статус доставки: {% if object.status == 'delivered' %} Доставлено {% else %} Не доставлено {% endif %}</h6>
                            <a class="card-title">Ответ сервера: {{ object.response }}</a>
                </div>
            </table>
        </div>
            <a href="{% url 'mailing:attempt_list' %}" type="button"
               class="w-100 btn btn-lg btn-outline-primary">Назад</a>
    </div>
{% endblock %}

mailing/templates/mailing/attempt_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container marketing text-center">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-mb-4 mx-auto text-center">
            <h1 class="display-4">{{ title }}</h1>
        </div>
        <div class="row">
            <div class="col-12">
                 {% regroup object_list|dictsortreversed:'time_of_sent' by mailing as mailing_list %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Email клиента</th>
                            <th>Дата отправки</th>
                            <th>Статус доставки</th>
                            <th>Подробнее</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for mailing in mailing_list %}
                            <tr>
                                <td colspan="4"><h3>{{ mailing.grouper }} </h3></td>
                            </tr>
                            {% for object in mailing.list %}
                                <tr>
                                    <td>{% if object.get_email %} {{ object.get_email }}{% else %} Email не указан {% endif %}</td>
                                    <td>{{ object.time_of_sent }}</td>
                                    <td>{% if object.status == 'delivered' %} Доставлено {% else %} Не доставлено {% endif %}</td>
                                    <td>
                                        <a href="{% url 'mailing:attempt_view' object.pk %}" class="btn btn-secondary">Посмотреть</a>
                                    </td>
                                </tr>

                            {% endfor %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/client_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-lg-12 m-5">
        <div class="card text-left">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Подтвердите удаление клиента {{ client.first_name }} {{ client.last_name }}
                    <input type="submit" class="btn btn-outline-danger" value="Подтверждаю">
                </form>
                <div class="content text-right">
                    <a href="{% url 'mailing:client_list' %}" class="btn btn-dark btn-sm m-2">Назад</a>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container marketing text-center" xmlns="http://www.w3.org/1999/html">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-mb-4 mx-auto text-center">
            <h1 class="display-4">{{ title }}</h1>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">Клиент</div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>Имя</td>
                                <td>{% if object.first_name %}{{ object.first_name | title }} {% endif %}
                    {% if object.last_name %}{{ object.last_name | title }} {% endif %}</td>
                            </tr>
                            <tr>
                                <td>Почта</td>
                                <td><p> {% if object.email is None %}Не указана {% else %}{{ object.email }}{% endif %}</p>
                                </td>
                            </tr>
                            <tr>
                                <td>Статус клиента</td>
                                <td>{% if object.is_active %} Активен {% else %} Неактивен {% endif %}</td>
                            </tr>
                            <tr>
                                <td>Комментарий</td>
                                <td> {% if object.comment %}{{ object.comment }}{% endif %}</td>
                            </tr>
                    </table>

                            <div class="card-footer">
                                <a href="{% url 'mailing:client_list' %}" class='btn btn-secondary'> Назад &laquo</a>
                            </div>
                    </div>
                </div>
            </div>
        </div>




    </div>

{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
<div class="content">
        <div class="col-lg-6 mb-5">
            <div class="card text-left">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value=" {% if object %}Сохранить{% else %}Создать{% endif %}">
                    <div class="content text-right">
                        <a href="{% url 'mailing:client_list' %}" class="btn btn-dark btn-sm m-2">Назад</a>
                    </div>
                </div>
            </div>
</div>
        </div>
    </form>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container marketing">
        {% if user.is_authenticated %}
            <a href="{% url 'mailing:client_create' %}" class="btn btn-dark text-right btn-sm">Добавить клиента</a>
        {% endif %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{ title }}</h1>

        </div>

    <div class="row">
        {{ object }}

        {% for object in object_list %}
            {% include 'includes/inc_mailing_card_client.html' %}
        {% endfor %}
    </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-lg-12 m-5">
        <div class="card text-left">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Подтвердите удаление рассылки {{ mailing.title }}
                    <input type="submit" class="btn btn-outline-danger" value="Подтверждаю">
                </form>
                <div class="content text-right">
                    <a href="{% url 'mailing:mailing_list' %}" class="btn btn-dark btn-sm m-2">Назад</a>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container marketing text-center" xmlns="http://www.w3.org/1999/html">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-mb-4 mx-auto text-center">
        <h1 class="display-4">{{ title }}</h1>
    </div>
    <div class="row">
    <div class="col-6">
        <div class="card">
        <div class="card-header">Рассылка</div>
            <div class="card-body">
                <table class="table">

                    <tr>
                        <td>Название</td>
                        <td>{{ object.title | title }}</td>
                    </tr>
                    <tr>
                        <td>Статус</td>
                        <td>{{ object.status| title }}</td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td>{{ object.date_of_creation }}</td>
                    </tr>
                    <tr>
                        <td>Частота рассылки</td>
                        <td>{{ object.frequency }}</td>

                    </tr>
                    <tr>
                        {% if product.get_active_version %}
                            <p> Активная версия - {{ product.get_active_version }}</p>
                        {% else %}
                            <p>Активной версии нет</p>
                        {% endif %}
                    </tr>


                </table>
                <div class="card-footer">
                    <a href="{% url 'mailing:mailing_list' %}" class='btn btn-secondary'> Назад &laquo</a>
                </div>
            </div>
        </div>


    </div>
      <form method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="card text-left">
                <div class="card-header text-center">
                    Сообщение
                </div>
                <div class="card-body">

                    <table class="table">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            <tr class="subject-form">
                                <td>
                                    {{ form.as_p }}
                                </td>
                            </tr>
                        {% endfor %}


                    </table>
                </div>
            </div>
        </div>
    </form>

    </div>

{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">

        <div class="col-lg-12 mb-5">
            <div class="card text-left">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value=" {% if object %}Сохранить{% else %}Создать{% endif %}">
                    <div class="content text-right">
                        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-dark btn-sm m-2">Назад</a>
                    </div>
                </div>
            </div>

        </div>
{#        {% if perms.mailing.change_mailing %}#}

    {% if not perms.mailing.can_disable_mailings or user.is_superuser %}
        <div class="col-12">
            <div class="card text-left">
                <div class="card-header text-center">
                    Сообщение
                </div>
                <div class="card-body">

                    <table class="table">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            <tr class="subject-form">
                                <td>
                                    {{ form.as_p }}
                                </td>
                            </tr>

                        {% endfor %}


                    </table>
{#                {% endif %}#}
                </div>
            </div>
        </div>
    {% endif %}
    </form>

{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container marketing">
        {% if user.is_authenticated %}
            <a href="{% url 'mailing:mailing_create' %}" class="btn btn-dark text-right btn-sm">Добавить рассылку</a>
        {% endif %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{ title }}</h1>

        </div>

    <div class="row">
        {{ object }}

        {% for object in object_list %}
            {% include 'includes/inc_mailing_card_mailing.html' %}
        {% endfor %}
    </div>
    </div>
{% endblock %}