blog/urls.py
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from django.urls import path
from . import views
from blog.views import PostListView, PostDetailView, index

app_name = BlogConfig.name

urlpatterns = [
    path('<int:pk>/', cache_page(60)(PostDetailView.as_view()), name='post_detail'),
    path('', views.index, name='index'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
                  path('', include('blog.urls', namespace='blog')),
                  path('admin/', admin.site.urls),
                  path('mailing/', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# path('users/', include('users.urls', namespace='users')),
# path('blog/', include('blog.urls', namespace='blog')),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from mailing.apps import MailingConfig
from django.urls import path
from . import views

from mailing.views import MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingDetailView, \
    ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, AttemptListView, \
    AttemptDetailView

app_name = MailingConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('create/', MailingCreateView.as_view(), name='mailing_create'),
    path('update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('attempt/', AttemptListView.as_view(), name='attempt_list'),
    path('attempt/<int:pk>/', AttemptDetailView.as_view(), name='attempt_view'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from users.apps import UsersConfig
from django.urls import path

from users.views import ProfileUpdateView, RegisterView, EmailVerify, MyLoginView, \
    CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, \
    CustomPasswordResetCompleteView, UserListView

app_name = UsersConfig.name


urlpatterns = [
    path('', MyLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='invalid_verify.html'), name='invalid_verify'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('user_list/', user_list, name='user_list'),
    path('user_list/', UserListView.as_view(), name='user_list'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import Group, Permission

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    is_email_verified = models.BooleanField(verbose_name='email подтвержден', default=False)
    is_blocked = models.BooleanField(verbose_name='пользователь заблокирован', default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            (
                "can_view_all_user",
                "Сan view all user"
            ),
            (
                "can_change_all_user",
                "Сan change all user"
            )
        ]

    @staticmethod
    def create_manager_group_and_permissions():
        manager_group, created = Group.objects.get_or_create(name='Менеджеры')
        if created:
            # Создание прав доступа для группы модераторов

            # Право на просмотр всех рассылок
            can_view_any_mailings = Permission.objects.get(codename='can_view_any_mailings')
            manager_group.permissions.add(can_view_any_mailings)

            # Право отключение рассылок
            can_disable_mailings = Permission.objects.get(codename='can_disable_mailings')
            manager_group.permissions.add(can_disable_mailings)

            # Права управления пользователями
            can_view_all_user = Permission.objects.get(codename='can_view_all_user')
            manager_group.permissions.add(can_view_all_user)

            can_change_all_user = Permission.objects.get(codename='can_change_all_user')
            manager_group.permissions.add(can_change_all_user)


# manager_group, created = Group.objects.get_or_create(name='Менеджеры')
# if created:
#     # Создание прав доступа для группы модераторов
#
#     # Право на просмотр всех рассылок
#     can_view_any_mailings = Permission.objects.get(codename='can_view_any_mailings')
#     manager_group.permissions.add(can_view_any_mailings)
#
#     # Право отключение рассылок
#     can_disable_mailings = Permission.objects.get(codename='can_disable_mailings')
#     manager_group.permissions.add(can_disable_mailings)
#
#     # Права управления пользователями
#     can_view_all_user = Permission.objects.get(codename='can_view_all_user')
#     manager_group.permissions.add(can_view_all_user)
#
#     can_change_all_user = Permission.objects.get(codename='can_change_all_user')
#     manager_group.permissions.add(can_change_all_user)

users/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm, PasswordResetForm, \
    SetPasswordForm
from django import forms
from django.core.exceptions import ValidationError

from mailing.forms import FormStyleMixin
from users.models import User
from users.utils import send_verify_email


class UserAuthenticationForm (AuthenticationForm):

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)

            if self.user_cache is None:
                raise self.get_invalid_login_error()

            if self.user_cache.is_email_verified is False:
                send_verify_email(self.request, self.user_cache)
                raise ValidationError(
                    'Email не верифицирован, проверьте свою почту',
                    code="invalid_login",
                )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class UserForm(FormStyleMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserRegisterForm(FormStyleMixin, UserCreationForm):
    class Meta:
        model = User
        # fields = ('first_name', 'last_name', 'phone', 'avatar', 'country', 'email', 'password1', 'password2')
        fields = ('email', 'password1', 'password2')


class CustomPasswordResetForm(FormStyleMixin, PasswordResetForm):
    email = forms.EmailField(
        label='Email',
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = User


class CustomSetPasswordForm(FormStyleMixin, SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        class Meta:
            model = User

users/views.py
from django.contrib.auth import get_user_model, login, authenticate
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import UpdateView, CreateView, ListView
from config.settings import EMAIL_HOST_USER
from users.models import User
from users.forms import UserForm, UserRegisterForm, UserAuthenticationForm, CustomSetPasswordForm, \
    CustomPasswordResetForm
from users.utils import send_verify_email
from django.shortcuts import render, get_object_or_404


class MyLoginView(LoginView):
    form_class = UserAuthenticationForm
    extra_context = {
        'title': 'Авторизация'
    }

    blocked_user_error_url = reverse_lazy('blog:index')

    # Если юзер заблокирован, не авторизуем его и перенаправляем на главную страницу
    def form_valid(self, form):
        user = form.get_user()
        if user.is_blocked and not user.is_superuser:
            self.request.session.flush()
            return redirect(self.blocked_user_error_url)
        return super().form_valid(form)


class ProfileUpdateView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('blog:index')

    def get_object(self, queryset=None):
        return self.request.user

    extra_context = {
        'title': 'Профиль'
    }


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    extra_context = {
        'title': 'Регистрация'
    }

    def post(self, request, *args, **kwargs):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            send_verify_email(request, user)

        context = {
            'form': form
        }

        return render(request, 'users/send_email.html', context)


User_data = get_user_model()


class EmailVerify(View):

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)
        print(uidb64)
        if user is not None and token_generator.check_token(user, token):
            user.is_email_verified = True
            user.save()
            login(request, user)
            return redirect('blog:index')
        else:
            return redirect('users:invalid_verify')

    @staticmethod
    def get_user(uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            print(uid)
            user = User_data.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User_data.DoesNotExist):
            user = None
        return user


# PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
class CustomPasswordResetView(PasswordResetView):
    email_template_name = 'users/password_reset_email.html'
    template_name = 'users/password_reset_form.html'
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy('users:password_reset_done')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = CustomSetPasswordForm
    success_url = reverse_lazy('users:password_reset_complete')
    template_name = 'users/password_reset_confirm.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'


class UserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = User
    template_name = 'users/user_list.html'
    context_object_name = 'users'
    login_url = reverse_lazy('users:user_list')
    extra_context = {
        'title': 'Список пользователей'
    }

    def test_func(self):
        manager = self.request.user.has_perm(
            "users.can_view_all_user") and self.request.user.has_perm(
            'users.can_change_all_user')
        # user1 = User.objects.get(email='iaiznura@gmail.com')
        # permissions = user1.get_all_permissions()
        # print(permissions)

        if manager:
            return True
        else:
            raise Http404()

    def post(self, request, *args, **kwargs):
        user_id = request.POST.get('user_id')
        user = get_object_or_404(User, id=user_id)
        user.is_blocked = not user.is_blocked
        user.save()
        return redirect('users:user_list')

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                </form>
            <div>
                                <a href="{% url 'users:password_reset' %}" class="btn btn-dark text-right btn-sm mt-2">Восстановить пароль</a>

            </div>
            </div>
            <div class="card-footer"></div>


        </div>


    </div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
  <p>Ваш пароль успешно сброшен. Ты можешь сейчас <a href="{% url 'users:login' %}">войти</a> со своим паролем.</p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
  <h2>Введите новый пароль</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success text-right btn-sm mt-2">Сохранить новый пароль</button>
  </form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
  <p>Мы отправили вам электронное письмо с инструкциями по сбросу пароля. Пожалуйста, проверьте свой почтовый ящик.</p>
{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
Чтобы сбросить пароль, нажмите на следующую ссылку:

http://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Если вы не запрашивали сброс пароля, проигнорируйте это письмо.
{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>Сброс пароля</h2>
  <p>Введите адрес электронной почты, и мы вышлем вам ссылку для сброса пароля.</p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-dark text-right btn-sm mt-2">Сбросить пароль</button>
  </form>
{% endblock %}

users/templates/users/send_email.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <div class="content mb-2"> Письмо для завершения регистрации направлено на ваш адрес</div>
                <a href="{% url 'mailing:mailing_list' %}" class="btn btn-dark text-right btn-sm mt-2">К рассылкам</a>

            </div>


        </div>


    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                <div class="content mb-2">{% if not user.is_email_verified %} <a>  Письмо для завершения регистрации будет направлено на ваш адрес </a> {% else %}

                            {% endif %}</div>
                    {% if user.is_authenticated %}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    {% else %}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                    {% endif %}
                      <a href="{% url 'users:password_reset' %}" class="btn btn-dark text-right">Восстановить пароль</a>

                </form>
            </div>
            <div class="card-footer"></div>


        </div>


    </div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container marketing text-center">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-mb-4 mx-auto text-center">
            <h1 class="display-4">{{ title }}</h1>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Имя пользователя</th>
                        <th>Email</th>
                        <th>Статус</th>
                        <th>Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        {% if not user.is_superuser %}
                        <tr>
                            <td>{{ user.first_name }} {{ user.last_name }}</td>
                            <td>{{ user.email }}</td>
                            <td>{% if not user.is_blocked %}Активен{% else %}Заблокирован{% endif %}</td>
                            <td>
                                <form method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="user_id" value="{{ user.id }}">
                                    {% if not user.is_blocked %}
                                        <button type="submit" class="btn btn-danger text-center btn-sm">Заблокировать
                                        </button>
                                    {% else %}
                                        <button type="submit" class="btn btn-success btn-sm">Разблокировать</button>
                                    {% endif %}
                                </form>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/verification_failed.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            Email {{ user.email }} не подтвержден
            Попробуйте залогиниться снова
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}"> Авторизация </a>
            <div class="card-body">

            </div>
        </div>
        <div class="card-footer"></div>

    </div>
{% endblock %}