blog/urls.py
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from django.urls import path
from . import views
from blog.views import PostListView, PostDetailView, index

app_name = BlogConfig.name

urlpatterns = [
    path('<int:pk>/', cache_page(60)(PostDetailView.as_view()), name='post_detail'),
    path('', views.index, name='index'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
                  path('', include('blog.urls', namespace='blog')),
                  path('admin/', admin.site.urls),
                  path('mailing/', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# path('users/', include('users.urls', namespace='users')),
# path('blog/', include('blog.urls', namespace='blog')),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from mailing.apps import MailingConfig
from django.urls import path
from . import views

from mailing.views import MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingDetailView, \
    ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, AttemptListView, \
    AttemptDetailView

app_name = MailingConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('create/', MailingCreateView.as_view(), name='mailing_create'),
    path('update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('attempt/', AttemptListView.as_view(), name='attempt_list'),
    path('attempt/<int:pk>/', AttemptDetailView.as_view(), name='attempt_view'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from users.apps import UsersConfig
from django.urls import path

from users.views import ProfileUpdateView, RegisterView, EmailVerify, MyLoginView, \
    CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, \
    CustomPasswordResetCompleteView, UserListView

app_name = UsersConfig.name


urlpatterns = [
    path('', MyLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='invalid_verify.html'), name='invalid_verify'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('user_list/', user_list, name='user_list'),
    path('user_list/', UserListView.as_view(), name='user_list'),

]

mailing/models.py
from django.db import models
from config import settings
from django.utils.timezone import now


NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='имя', **NULLABLE)
    last_name = models.CharField(max_length=150, verbose_name='фамилия', **NULLABLE)
    email = models.EmailField(max_length=150, verbose_name='почта', **NULLABLE)
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='кем создан', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активен')

    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailing(models.Model):
    ONCE = 'один раз'  # временно
    DAILY = 'раз в день'
    WEEKLY = 'раз в неделю'
    MONTHLY = 'раз в месяц'

    FREQUENCY_CHOICES = [
        (ONCE, 'один раз'),
        (DAILY, 'раз в день'),
        (WEEKLY, 'раз в неделю'),
        (MONTHLY, 'раз в месяц'),
    ]

    CREATED = 'Создана'
    LAUNCHED = 'Запущена'
    COMPLETED = 'Завершена'

    SELECT_STATUS = [
        (CREATED, 'Создана'),
        (LAUNCHED, 'Запущена'),
        (COMPLETED, 'Завершена'),
    ]

    date_of_creation = models.DateTimeField(default=now, verbose_name='Дата создания')
    start_date = models.DateField(default=now, verbose_name='Дата начала рассылки')
    end_date = models.DateField(default=now, verbose_name='Дата окончания рассылки', **NULLABLE)
    frequency = models.CharField(max_length=14, choices=FREQUENCY_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=50, default='Создана', choices=SELECT_STATUS, verbose_name='Статус')
    clients = models.ManyToManyField(Client)
    title = models.CharField(max_length=50, verbose_name='Название рассылки', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Кем создана', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активна')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            (
                "can_view_any_mailings",
                "Сan view any mailings"
            ),
            (
                "can_disable_mailings",
                "Can disable mailings"
            )]


class Message(models.Model):
    subject = models.CharField(max_length=254, verbose_name='Тема')
    message = models.TextField(verbose_name='Сообщение')
    date_of_creation = models.DateTimeField(default=now, verbose_name='дата создания')
    mailing = models.ForeignKey(Mailing, verbose_name='рассылка', on_delete=models.CASCADE)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Attempt(models.Model):
    DELIVERED = 'delivered'
    NOT_DELIVERED = 'not_delivered'

    STATUS = (
        (DELIVERED, 'доставлено'),
        (NOT_DELIVERED, 'не доставлено'),
    )

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')
    time_of_sent = models.DateTimeField(default=now, verbose_name='Время рассылки')
    status = models.CharField(max_length=100, choices=STATUS, verbose_name='Статус')
    response = models.TextField(verbose_name='Ответ сервера', **NULLABLE)

    def __str__(self):

        return f"{message.subject} - {self.time_of_sent}"

    def get_email(self):
        message = Message.objects.get(mailing=self.mailing)
        # client = Client.objects.get(mailing=self.mailing)
        client = self.mailing.clients.first()
        return f'{client.email}'

    class Meta:
        verbose_name = 'Попытка отправки'
        verbose_name_plural = 'Попытки отправки'

mailing/forms.py
from django import forms

from mailing.models import Mailing, Message, Client


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        # fields = '__all__'
        exclude = ('date_of_creation', 'owner',)


class MailingFormManager(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('is_active',)


class MessageForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'


class MessageDetailForm(FormStyleMixin, forms.ModelForm):
    subject = forms.CharField(label='Тема письма',
                              widget=forms.Textarea(attrs={'cols': 40, 'rows': 2, 'readonly': 'readonly'}))
    message = forms.CharField(label='Сообщение',
                              widget=forms.Textarea(attrs={'cols': 40, 'rows': 3, 'readonly': 'readonly'}))

    date_of_creation = forms.DateTimeField(label='Дата создания',
                                           widget=forms.Textarea(attrs={'cols': 40, 'rows': 1, 'readonly': 'readonly'}))

    class Meta:
        model = Message
        fields = ('subject', 'message', 'date_of_creation')


class ClientForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Client
        # fields = '__all__'
        exclude = ('date_of_creation', 'owner',)

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from mailing.forms import MailingForm, MessageForm, MessageDetailForm, ClientForm, MailingFormManager
from mailing.models import Mailing, Message, Client, Attempt
from users.models import User


# Create your views here.
class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    extra_context = {
        'title': 'Список рассылок'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        # user1 = User.objects.get(email='iaiznura@gmail.com')
        # permissions = user1.get_all_permissions()
        # print(permissions)
        manager = self.request.user.has_perm("mailing.can_view_any_mailings") and self.request.user.is_authenticated
        if manager:
            return queryset
        else:
            # queryset = queryset.filter(owner=self.request.user, is_active=True)
            queryset = queryset.filter(owner=self.request.user)
            return queryset


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(Mailing, Message, form=MessageDetailForm, extra=0, can_delete=False)
        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            MessageFormset = inlineformset_factory(Mailing, Message, form=MessageDetailForm, extra=0, can_delete=False)
            context_data['formset'] = MessageFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    # fields = ('title', 'frequency', 'status',)
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')
    extra_context = {
        'title': 'Создание рассылки'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(Mailing, Message, form=MessageForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        form.instance.owner = self.request.user if self.request.user.is_authenticated else None
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_form.html"
    success_url = reverse_lazy('mailing:mailing_list')
    extra_context = {
        'title': 'Редактирование'
    }

    def get_form_class(self):
        class_form = MailingFormManager
        mailing = self.get_object()
        if not self.request.user.has_perm('mailing.can_disable_mailings'):
            class_form = MailingForm
        if self.request.user == mailing.owner or self.request.user.is_superuser:
            class_form = MailingForm
        return class_form

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(Mailing, Message, form=MessageForm, extra=1, max_num=1)
        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)
        return context_data

    def test_func(self):
        mailing = self.get_object()
        manager = self.request.user.has_perm(
            "mailing.can_view_any_mailings") and self.request.user.has_perm(
            'mailing.can_disable_mailings')
        if manager:
            return True
        else:
            return self.request.user == mailing.owner

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        form.instance.author = self.request.user if self.request.user.is_authenticated else None
        return super().form_valid(form)


class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')

    def test_func(self):
        mailing = self.get_object()
        if self.request.user.is_superuser:
            return True
        else:
            return self.request.user == mailing.owner


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {
        'title': 'Список клиентов'
    }


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('first_name', 'last_name', 'email', 'comment',)
    # form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')
    extra_context = {
        'title': 'Создание рассылки'
    }

    def handle_no_permission(self):
        raise PermissionDenied("Вы не являетесь автором этого продукта.")


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    # fields = ('first_name', 'last_name', 'email', 'comment',)
    form_class = ClientForm
    template_name = "mailing/client_form.html"
    success_url = reverse_lazy('mailing:client_list')
    extra_context = {
        'title': 'Редактирование'
    }


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:mailing_list')


class AttemptListView(LoginRequiredMixin, ListView):
    model = Attempt
    extra_context = {
        'object_list': Attempt.objects.all(),
        'title': 'Статус рассылок'
    }


class AttemptDetailView(LoginRequiredMixin, DetailView):
    model = Attempt
    extra_context = {
        'title': 'Рассылка'
    }

mailing/templates/includes/inc_mailing_card_client.html
<div class="col-lg-4">
    <div class="card m-2 text-center">
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <h3> {% if object.first_name %}{{ object.first_name | title }} {% endif %}
                    {% if object.last_name %}{{ object.last_name | title }}{% endif %}</h3>
                <p> Статус клиента - {% if object.is_active %} Активен {% else %} Неактивен {% endif %}</p>
{#                {% if user.is_authenticated %}#}
                <p><a href="{% url 'mailing:client_delete' object.pk %}" class="btn btn-danger text-center btn-sm">Удалить </a>
                </p>
                <p><a href="{% url 'mailing:client_update' object.pk %}" class="btn btn-warning text-center btn-sm">Редактировать </a>
                </p>
{#                {% endif %}#}
                <p><a class="btn btn-secondary"
                      href="{% url 'mailing:client_detail' object.pk %}" role="button">Подробнее &raquo;</a></p>

            </ul>
        </div>
    </div>

</div>

mailing/templates/includes/inc_mailing_card_mailing.html
{#<div class="col-lg-4">#}
{#    <div class="card m-2 text-center">#}
{#        <div class="card-body">#}
{#            <ul class="list-group list-group-flush">#}
{#                <h3> {{ object.title | title | truncatechars:18}}</h3>#}
{#                <p> Статус рассылки: {{ object.status }}</p>#}
{#                <p> Создана: {{ object.date_of_creation }}</p>#}
{#                <p> Частота рассылки - {{ object.frequency }} </p>#}
{#                <p> {% if object.is_active %} Рассылка активна {% else %} Рассылка неактивна {% endif %}</p>#}
{#                {% if user.is_authenticated %}#}
{#                <p><a href="{% url 'mailing:mailing_delete' object.pk %}" class="btn btn-danger text-center btn-sm">Удалить </a>#}
{#                </p>#}
{#                <p><a href="{% url 'mailing:mailing_update' object.pk %}" class="btn btn-warning text-center btn-sm">Редактировать </a>#}
{#                </p>#}
{#                {% endif %}#}
{#                <p><a class="btn btn-secondary"#}
{#                      href="{% url 'mailing:mailing_detail' object.pk %}" role="button">Подробнее &raquo;</a></p>#}
{##}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{##}
{#</div>#}


<div class="col-lg-4">
    <div class="card m-2">
        <div class="card-body">
            <h3 class="card-title text-center mb-3">{{ object.title | title | truncatechars:18}}</h3>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Статус рассылки: {{ object.status }}</li>
                <li class="list-group-item">Создана: {{ object.date_of_creation }}</li>
                <li class="list-group-item">Частота рассылки: {{ object.frequency }}</li>
                <li class="list-group-item">{% if object.is_active %}
                    <span class="text-success">Рассылка активна</span>
                    {% else %}
                    <span class="text-danger">Рассылка неактивна</span>
                    {% endif %}
                </li>
            </ul>
        </div>
        <div class="card-footer d-flex">
            <a class="btn btn-outline-secondary btn-sm ml-auto"
               href="{% url 'mailing:mailing_detail' object.pk %}" role="button">Подробнее</a>
            {% if user.is_authenticated %}
                <a href="{% url 'mailing:mailing_update' object.pk %}"
                   class="btn btn-outline-warning btn-sm ml-auto">Редактировать</a>
                <a href="{% url 'mailing:mailing_delete' object.pk %}"
                   class="btn btn-outline-danger btn-sm ml-auto">Удалить</a>
            {% endif %}
        </div>
    </div>
</div>

mailing/templates/includes/inc_mailing_menu.html
{#{% load mediapath %}#}
{#<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">#}
{#    <h5 class="my-0 mr-md-auto font-weight-normal"><img class="img-fluid" src="../../media/Cuckoo.png" alt="" width="50" height="50"> Cuckoo</h5>#}
{##}
{#    <nav class="ms-5">#}
{#        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:index' %}">Главная</a>#}
{#        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:attempt_list' %}">Статус рассылок</a>#}
{##}
{#        {% if perms.users.can_view_all_user and perms.users.can_change_all_user %}#}
{#            <a class="p-2 btn btn-outline-primary" href="{% url 'users:user_list' %}">Список пользователей</a>#}
{#        {% endif %}#}
{#        {% if user.is_authenticated %}#}
{#            <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:mailing_list' %}">Рассылки</a>#}
{#            <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:client_list' %}">Клиенты</a>#}
{#            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>#}
{#            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>#}
{#        {% else %}#}
{#            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>#}
{#            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Авторизация</a>#}
{#        {% endif %}#}
{#    </nav>#}
{#    <style>#}
{#        main {#}
{#            margin-top: 10px;#}
{#        }#}
{#    </style>#}
{#</div>#}



{% load mediapath %}

<nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="../../media/Cuckoo.png" alt="" width="50" height="50" class="d-inline-block align-text-top">
            Cuckoo
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mailing:attempt_list' %}">Статус рассылок</a>
                </li>
                {% if perms.users.can_view_all_user and perms.users.can_change_all_user %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:user_list' %}">Список пользователей</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:mailing_list' %}">Рассылки</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:client_list' %}">Клиенты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Авторизация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>